# Generated by Django 3.2.8 on 2022-03-03 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0004_auto_20220303_0319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
