# Generated by Django 3.2.8 on 2022-03-03 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0009_alter_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
